Repository kids-first/kf-api-study-creator, pull requests merged in 2019-02, with the labels that each got.

#7 📝 Add docs site
  .circleci/config.yml
  .gitignore
  README.md
  dev-requirements.txt
  docs/_static/images/study_creator.svg
  docs/conf.py
  docs/index.rst
Labels: documentation

#8 📝 Base docs
  README.md
  docs/_static/study_creator.png
  docs/authentication.rst
  docs/conf.py
  docs/index.rst
  docs/model.rst
  docs/uploads.rst
Labels: documentation

#18 ✨File upload
  creator/files/schema.py
  creator/files/tests.py
  creator/schema.py
  creator/studies/models.py
  creator/studies/tests.py
  creator/urls.py
  dev-requirements.txt
  docs/uploads.rst
  pytest.ini
  requirements.txt
  tests/data/manifest.txt
  tests/test_query.py
  tests/test_upload.py
Labels: feature

#19 🚨Add Pep8 linting
  .circleci/config.yml
  creator/files/factories.py
  creator/files/management/commands/fakefiles.py
  creator/files/schema.py
  creator/schema.py
  creator/studies/management/commands/fakestudies.py
  creator/studies/models.py
  creator/studies/schema.py
  dev-requirements.txt
  pytest.ini
  tests/test_query.py
  tests/test_upload.py
Labels: refactor

#27 ✨ Add cors-headers package
  creator/settings.py
  requirements.txt
Labels: feature

#28 ♻️ Relate Files to Studies instead of batches
  creator/files/factories.py
  creator/files/migrations/0001_initial.py
  creator/files/models.py
  creator/files/schema.py
  tests/test_upload.py
Labels: refactor

#30 🔧 Exempt csrf from graphql endpoint
  creator/urls.py
Labels: feature

#31 ♻️ Rename FileEssence to File
  creator/files/admin.py
  creator/files/factories.py
  creator/files/management/commands/fakefiles.py
  creator/files/migrations/0001_initial.py
  creator/files/models.py
  creator/files/schema.py
Labels: refactor

#32 ✨ Add dotenv
  creator/wsgi.py
  manage.py
  requirements.txt
Labels: feature

#33 ✨ S3 Uploads
  .circleci/config.yml
  .env
  .gitignore
  creator/files/migrations/0002_auto_20190225_1937.py
  creator/files/models.py
  creator/files/schema.py
  creator/settings.py
  dev-requirements.txt
  dev.env
  pytest.ini
  requirements.txt
  tests/conftest.py
  tests/test_upload.py
Labels: feature

#39 🐛 Rename batch to study
  creator/files/factories.py
Labels: bug

#40 ♻️ Add file to createFile response
  creator/files/schema.py
  tests/test_upload.py
Labels: refactor

#42 🗃 Add new study fields
  creator/studies/factories.py
  creator/studies/management/commands/syncstudies.py
  creator/studies/migrations/0002_auto_20190226_1748.py
  creator/studies/models.py
Labels: feature

#43 🐘 Switch to PostgreSQL
  .circleci/config.yml
  creator/settings.py
  docker-compose.yml
  requirements.txt
Labels: refactor

#44 🐛 Increase study name field max length to 500
  creator/studies/migrations/0003_auto_20190226_2048.py
  creator/studies/models.py
Labels: bug

#46 ✏️ Change manifest file type enum
  creator/files/factories.py
  creator/files/migrations/0003_auto_20190226_2058.py
  creator/files/models.py
Labels: refactor

#47 ♻️ Add dev stage to Dockerfile
  Dockerfile
  bin/dev_entrypoint.sh
  bin/entrypoint.sh
  docker-compose.yml
  docs/development/quickstart.rst
  docs/index.rst
Labels: refactor

#48 ✨ Add download endpoint
  creator/files/models.py
  creator/files/views.py
  creator/urls.py
  tests/conftest.py
  tests/data/data.csv
  tests/test_download.py
Labels: feature

#49 ✨ Set max upload file size
  creator/files/schema.py
  creator/settings.py
  tests/test_upload.py
Labels: feature

#50 ♻️ Refactor to use upload_file fixture
  tests/test_download.py
  tests/test_upload.py
Labels: refactor

#53 ✨ Add download field to GraphQL data response
  creator/files/models.py
  creator/files/schema.py
  tests/test_download.py
Labels: feature

#51 ✨ Add Ego JWT authentication
  creator/middleware.py
  creator/migrations/0001_initial.py
  creator/migrations/__init__.py
  creator/models.py
  creator/settings.py
  creator/studies/schema.py
  requirements.txt
  tests/conftest.py
  tests/test_query.py
Labels: feature

#54 ✨ Add upload authorization
  creator/files/schema.py
  tests/conftest.py
  tests/test_download.py
  tests/test_upload.py
Labels: feature
