Repository kids-first/kf-api-study-creator, pull requests merged in 2019-09, with the labels that each got.

#283 ✨ Add project study filter
  creator/projects/schema.py
Labels: feature

#284 🔧 Make requests timout configurable
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
Labels: feature

#289 ✨ Emit events for projects
  creator/events/migrations/0003_project_events.py
  creator/events/models.py
  creator/projects/cavatica.py
  creator/projects/schema.py
  creator/studies/schema.py
  tests/__init__.py
  tests/conftest.py
  tests/events/test_projects.py
  tests/events/test_studies.py
  tests/projects/fixtures.py
  tests/projects/test_cavatica.py
  tests/projects/test_cavatica_sync.py
  tests/studies/test_create_study.py
Labels: feature

#291 ✏️ Rename datetime filters
  creator/events/schema.py
  tests/events/test_event_auth.py
Labels: refactor

#293 ✨ Mark studies as deleted from dataservice
  creator/studies/management/commands/syncstudies.py
  creator/studies/migrations/0010_study_deleted.py
  creator/studies/models.py
  creator/studies/schema.py
Labels: feature

#294 ✨ Make bucket modifiable
  creator/studies/schema.py
Labels: feature

#298 🔧 Load database creds from S3
  bin/entrypoint.sh
Labels: devops

#296 🔧 Update port for study creator
  docker-compose.yml
Labels: devops

#302 Terraform 0.12 Upgrade
  Jenkinsfile
Labels: devops

#300 ✨ Integrate bucketservice
  bin/entrypoint.sh
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/studies/bucketservice.py
  creator/studies/schema.py
  docs/bucketservice.rst
  docs/index.rst
  tests/studies/test_bucketservice.py
Labels: feature

#304 📝 Add page on Data Service settings
  docs/dataservice.rst
  docs/index.rst
Labels: documentation

#306 ✨ Add updateProject mutation
  creator/projects/models.py
  creator/projects/schema.py
  creator/schema.py
  tests/projects/test_update_project.py
Labels: feature
