Repository kids-first/kf-api-study-creator, pull requests merged in 2019-08, with the labels that each got.

#219 ✨Add integration with dataservice for new studies
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/studies/migrations/0005_study_name_nullable.py
  creator/studies/models.py
  creator/studies/schema.py
  dev-requirements.txt
  docker-compose.dataservice.yml
  docs/authorization.rst
  docs/development/quickstart.rst
  tests/studies/test_create_study.py
Labels: feature

#224 🐳 Use common postgres versions for containers
  docker-compose.yml
Labels: devops

#223 🐛 Don't try to recreate dev user
  bin/dev_entrypoint.sh
Labels: bug

#225 ✨ Add updateStudy mutation
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/studies/schema.py
  docker-compose.dataservice.yml
  tests/studies/test_update_study.py
Labels: feature

#227 ✨ Create CavaticaProject model
  creator/projects/__init__.py
  creator/projects/apps.py
  creator/projects/migrations/0001_add_projects.py
  creator/projects/migrations/__init__.py
  creator/projects/models.py
  creator/projects/schema.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
Labels: feature

#234 🐳 Fix docker environment formatting
  docker-compose.dataservice.yml
Labels: bug, devops

#235 ⬆️ Bump up moto to version 1.3.10
  dev-requirements.txt
Labels: devops

#229 ✨ Create new projects in Cavatica on study creation
  creator/projects/cavatica.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/studies/schema.py
  docker-compose.yml
  docs/development/quickstart.rst
  requirements.txt
  tests/projects/test_cavatica.py
  tests/studies/test_create_study.py
Labels: feature

#242 ✨ Add workflow_type field to project model
  creator/projects/cavatica.py
  creator/projects/migrations/0002_project_workflow_type.py
  creator/projects/models.py
  creator/projects/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/projects/test_cavatica.py
Labels: feature

#238 ✨ Add release date to study
  creator/studies/migrations/0006_add_release_date.py
  creator/studies/models.py
  creator/studies/schema.py
Labels: feature

#240 ♻️ Rename event filter arguments
  creator/events/schema.py
  tests/events/test_event_auth.py
Labels: refactor

#243 🐛 Fix project creation error with naming
  creator/projects/cavatica.py
  creator/projects/models.py
Labels: bug

#244 ✨ Study description
  .gitignore
  creator/studies/migrations/0007_study_description.py
  creator/studies/models.py
  creator/studies/schema.py
  dev-requirements.txt
  tests/studies/test_create_study.py
  tests/studies/test_update_study.py
Labels: feature

#245 🔥 Remove batches
  creator/studies/factories.py
  creator/studies/management/commands/fakestudies.py
  creator/studies/migrations/0008_remove_batch.py
  creator/studies/models.py
  creator/studies/schema.py
Labels: refactor

#250 ✨ Add sync projects mutation
  creator/projects/cavatica.py
  creator/projects/schema.py
  creator/schema.py
  tests/projects/test_cavatica_sync.py
Labels: feature

#249 ✨ New study fields
  creator/studies/migrations/0009_study_grant_fields.py
  creator/studies/models.py
  creator/studies/schema.py
  tests/studies/test_create_study.py
  tests/studies/test_update_study.py
Labels: feature

#251 📝 Add descriptions to all queries
  creator/events/schema.py
  creator/files/schema/__init__.py
  creator/files/schema/file.py
  creator/files/schema/version.py
  creator/projects/schema.py
  creator/schema.py
  creator/studies/schema.py
Labels: documentation

#252 ✨ Create events when studies are created
  creator/events/models.py
  creator/studies/schema.py
  tests/events/test_studies.py
Labels: feature

#253 📝 Add page about Cavatica integration
  docs/cavatica.rst
  docs/development/quickstart.rst
  docs/index.rst
Labels: documentation

#254 🔧 Remove default Cavatica token settings
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  docker-compose.yml
  tests/projects/test_cavatica.py
  tests/projects/test_cavatica_sync.py
  tests/studies/test_create_study.py
Labels: bug, refactor

#255 ✨ Add linkProject mutation
  creator/projects/factories.py
  creator/projects/schema.py
  creator/schema.py
  tests/projects/test_link_project.py
Labels: feature

#256 🐛 Make Cavatica times timezone aware
  creator/projects/cavatica.py
Labels: bug

#258 ✨ Add unlinkProject mutation
  creator/projects/schema.py
  creator/schema.py
  tests/projects/test_link_project.py
Labels: feature

#260 🐛 Fix study createdAt date parsing
  creator/studies/schema.py
Labels: bug

#261 🐛 Add release date to mutations
  creator/studies/schema.py
  tests/studies/test_create_study.py
  tests/studies/test_update_study.py
Labels: bug

#262 📝 Input docs
  creator/schema.py
  creator/studies/schema.py
Labels: documentation

#264 ✨ Add workflows argument to createStudy mutation
  creator/projects/models.py
  creator/projects/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/studies/schema.py
  tests/projects/test_cavatica.py
  tests/studies/test_create_study.py
Labels: feature

#266 🗃 Add migration to adjust workflow choices
  creator/projects/migrations/0003_project_update_workflows.py
  creator/projects/schema.py
  tests/studies/test_create_study.py
Labels: bug

#267 ✨ Mark projects as deleted on sync
  creator/projects/cavatica.py
  creator/projects/migrations/0004_project_deleted_field.py
  creator/projects/models.py
  creator/projects/schema.py
  tests/projects/test_cavatica_sync.py
Labels: feature

#276 ✨ Add createProject mutation
  creator/projects/schema.py
  creator/schema.py
  pytest.ini
  tests/projects/__init__.py
  tests/projects/conftest.py
  tests/projects/test_cavatica.py
  tests/projects/test_cavatica_sync.py
  tests/projects/test_new_project.py
Labels: feature

#279 ♻️ Use ID type for study argument in createProject mutation
  creator/projects/schema.py
  tests/projects/test_new_project.py
Labels: refactor

#278 🐛 Fix datetime issues
  creator/projects/cavatica.py
  creator/studies/schema.py
Labels: bug

#280 ✨ Add overrides for user's roles and groups
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/users/schema.py
  docker-compose.yml
  docs/development/quickstart.rst
  tests/users/test_profile.py
Labels: feature, refactor
