Repository kids-first/kf-api-study-creator, pull requests merged in 2019-10, with the labels that each got.

#311 ✨ Add email notification field
  creator/migrations/0007_add_email_notify.py
  creator/models.py
  creator/users/schema.py
  tests/users/test_profile.py
Labels: feature

#312 🐛 Fix the user email/slack notify toggle mutation
  creator/users/schema.py
  tests/users/test_profile.py
Labels: bug

#313 ✅ Add Codecov test as default pull request checking method
  .circleci/config.yml
  README.md
  dev-requirements.txt
Labels: devops
