Repository kids-first/kf-api-study-creator, pull requests merged in 2019-06, with the labels that each got.

#191 ✨ Add creator field to files and versions
  creator/files/migrations/0011_add_creator.py
  creator/files/models.py
  creator/files/schema.py
  tests/files/test_upload.py
Labels: feature

#192 🐛 Use version file_name for downloads
  creator/files/views.py
Labels: bug

#193 ♻️ Split file and version upload mutations
  creator/files/schema.py
  creator/files/schema/__init__.py
  creator/files/schema/file.py
  creator/files/schema/version.py
  creator/schema.py
  tests/conftest.py
  tests/files/test_upload.py
Labels: refactor

#194 ✨ Add myProfile query
  creator/users/schema.py
  tests/users/test_profile.py
Labels: feature

#197 ✨ Add user notification settings
  creator/migrations/0005_add_subscriptions.py
  creator/migrations/0006_add_slack_settings.py
  creator/models.py
  creator/schema.py
  creator/users/schema.py
  tests/users/test_profile.py
  tests/users/test_subscriptions.py
Labels: feature

#198 ✨ Add events
  creator/events/__init__.py
  creator/events/apps.py
  creator/events/migrations/0001_initial.py
  creator/events/migrations/0002_correct_enums.py
  creator/events/migrations/__init__.py
  creator/events/models.py
  creator/events/schema.py
  creator/events/signals.py
  creator/files/factories.py
  creator/files/schema/file.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/conftest.py
  tests/events/test_event_auth.py
  tests/events/test_files.py
  tests/events/test_versions.py
  tests/files/test_upload.py
  tests/test_fields.py
Labels: feature

#200 ✨ Add creator field to tokens
  creator/files/migrations/0012_add_token_creator.py
  creator/files/models.py
  creator/files/schema/__init__.py
  tests/files/test_dev_tokens.py
Labels: feature

#205 ♻️ Update fake data for files and versions
  creator/files/factories.py
Labels: refactor

#206 🐛 raises study short_name character limit to 500
  creator/studies/migrations/0004_update_short_name_limit.py
  creator/studies/models.py
Labels: bug

#208 📝 Update docs
  docs/authentication.rst
  docs/authorization.rst
  docs/index.rst
Labels: documentation
