Repository kids-first/kf-api-study-creator, pull requests merged in 2019-03, with the labels that each got.

#56 🐛 Take kwargs on study resolver
  creator/studies/schema.py
Labels: bug

#61 ✨ Add manager for custom user model
  creator/models.py
Labels: bug

#55 👷 Add Jenkinsfile
  Dockerfile
  Jenkinsfile
  bin/entrypoint.sh
  creator/settings.py
  pytest.ini
  requirements.txt
Labels: feature

#65 ✨ Add permission checking to allFiles query
  creator/files/schema.py
  tests/test_query.py
Labels: feature

#66 ✨ Add permission checking to allVersions query
  creator/files/schema.py
  tests/test_query.py
Labels: feature

#67 ✨ Add version download endpoint
  creator/files/views.py
  creator/urls.py
  tests/test_download.py
Labels: feature

#68 ✨ File ids
  creator/fields.py
  creator/files/factories.py
  creator/files/migrations/0001_initial.py
  creator/files/migrations/0002_auto_20190225_1937.py
  creator/files/migrations/0003_auto_20190226_2058.py
  creator/files/models.py
  creator/files/views.py
  requirements.txt
  tests/test_download.py
  tests/test_fields.py
Labels: feature

#71 🔧 Split settings files
  creator/settings/__init__.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/wsgi.py
  docker-compose.yml
  docs/development/quickstart.rst
  manage.py
  pytest.ini
Labels: feature

#72 🐛 Installs psycopg2-binary
  requirements.txt
Labels: bug

#73 🐛 Don't create admin if already exists
  bin/dev_entrypoint.sh
Labels: bug

#76 🔧 Bypass authentication in development
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
Labels: feature

#81 🔧 Display graphiql on site root
  creator/urls.py
Labels: bug

#79 ✨ Sync studies from dataservice
  bin/entrypoint.sh
  requirements.txt
Labels: feature

#80 ♻️ Refactor test by adding prep-file fixture
  tests/conftest.py
  tests/test_download.py
  tests/test_query.py
  tests/test_upload.py
Labels: refactor

#82 ♻️ Increate upload file size limitation to 537M
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
Labels: refactor

#83 🔧 Load PRELOAD_DATA from env
  docker-compose.yml
Labels: feature

#88 🐛 Sync bucket names
  creator/studies/management/commands/.syncstudies.py.swo
  creator/studies/management/commands/syncstudies.py
  creator/urls.py
Labels: bug

#89 ✨ Upload error handling
  creator/files/schema.py
  tests/test_upload.py
Labels: bug

#91 ✨Add file mutation
  creator/files/schema.py
  creator/schema.py
  tests/conftest.py
  tests/test_query.py
Labels: feature

#93 📝 Update documentation for permissions
  docs/authentication.rst
  docs/development/quickstart.rst
  docs/model.rst
Labels: documentation

#94 ✨Add version download field
  creator/files/models.py
  creator/files/schema.py
  tests/test_download.py
Labels: feature

#98 ♻️ Reformat file name
  creator/files/views.py
  tests/data/name with spaces.txt
  tests/test_download.py
Labels: refactor

#99 ♻️ Refactor download function
  creator/files/views.py
  creator/urls.py
Labels: refactor

#92 ✨ Get entities by kf id
  creator/files/schema.py
  creator/studies/schema.py
  tests/test_authorized.py
Labels: feature

#101 ♻️ Update documentation for Uploading with GraphQL
  docs/uploads.rst
Labels: documentation

#103 ✨Add download auth checking
  creator/files/views.py
  tests/test_download.py
Labels: feature

#105 ♻️ Refactor download error
  creator/files/views.py
  tests/test_download.py
Labels: refactor

#106 ✨ JWT key validation
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/conftest.py
  tests/keys/other_private_key.pem
  tests/keys/private_key.pem
  tests/keys/public_key.pem
  tests/test_ego_signing.py
Labels: feature

#107 🐳 Add service to kf-data-stack network
  README.md
  docker-compose.yml
  docs/development/quickstart.rst
Labels: devops, documentation

#113 📝Update uploads page
  docs/uploads.rst
Labels: documentation

#116 🚨 Add pycodestyle
  creator/files/schema.py
  creator/schema.py
  creator/studies/models.py
  dev-requirements.txt
  pytest.ini
Labels: refactor

#117 🗃 Add missing migration
  creator/migrations/0002_auto_20190321_1936.py
Labels: refactor

#120 ✨ Add auth0
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/authentication/test_middleware.py
  tests/conftest.py
  tests/keys/jwks.json
  tests/test_ego_signing.py
Labels: feature

#125 ✨ Signed download urls
  creator/files/migrations/0002_downloadtoken.py
  creator/files/models.py
  creator/files/views.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/urls.py
  docs/authentication.rst
  docs/downloads.rst
  docs/index.rst
  tests/test_download.py
Labels: feature

#128 ✨ Require study id in download to be valid
  creator/files/views.py
  tests/test_download.py
Labels: bug

#129 ✨ Add mutation to make signed url
  creator/files/schema.py
  creator/schema.py
  docs/downloads.rst
  tests/test_mutation.py
Labels: feature

#130 🔥 Remove django admin
  creator/files/admin.py
  creator/studies/admin.py
  creator/urls.py
Labels: refactor

#132 ♻️ Cache JWKS for future validation
  creator/middleware.py
  tests/authentication/test_middleware.py
Labels: bug, refactor

#134 ✨ Service token auth
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/authentication/test_middleware.py
  tests/conftest.py
  tests/test_download.py
  tests/test_mutation.py
Labels: feature

#135 ✨ Add file type to update mutation
  creator/files/migrations/0003_other_file_type.py
  creator/files/models.py
  creator/files/schema.py
  tests/test_mutation.py
  tests/test_query.py
Labels: feature

#136 ✨ Add deleteFile mutation
  creator/files/schema.py
  creator/schema.py
  tests/test_mutation.py
Labels: feature

#138 ✨ Add developer tokens
  creator/files/migrations/0004_dev_tokens.py
  creator/files/models.py
  creator/files/schema.py
  creator/files/views.py
  creator/schema.py
  docs/downloads.rst
  tests/conftest.py
  tests/test_dev_tokens.py
  tests/test_mutation.py
Labels: feature
