Repository kids-first/kf-api-study-creator, pull requests merged in 2020-08, with the labels that each got.

#442 🔧 Increase task queue timeouts
  creator/settings/production.py
Labels: bug, devops

#443 ✅ Add test for unfound nodes
  creator/projects/schema.py
  creator/referral_tokens/schema.py
  creator/studies/nodes.py
  tests/test_not_found.py
Labels: refactor

#445 ♻️ Refactor schemas
  creator/buckets/mutations.py
  creator/buckets/schema.py
  creator/files/mutations/__init__.py
  creator/files/mutations/download.py
  creator/files/mutations/file.py
  creator/files/mutations/version.py
  creator/files/nodes/__init__.py
  creator/files/nodes/file.py
  creator/files/nodes/version.py
  creator/files/schema/__init__.py
  creator/files/schema/download.py
  creator/files/schema/file.py
  creator/files/schema/version.py
  creator/projects/mutations.py
  creator/projects/schema.py
  creator/referral_tokens/mutations.py
  creator/referral_tokens/schema.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/status/__init__.py
  creator/status/apps.py
  creator/status/schema.py
  creator/users/mutations.py
  creator/users/schema.py
Labels: refactor

#444 ✅ Add test for model strings
  tests/test_fields.py
  tests/test_models.py
Labels: refactor

#446 ♻️ Replace usernames in events with full names
  creator/buckets/mutations.py
  creator/events/signals.py
  creator/files/mutations/file.py
  creator/management/commands/setup_test_user.py
  creator/projects/cavatica.py
  creator/projects/mutations.py
  creator/referral_tokens/mutations.py
  creator/slack.py
  creator/studies/mutations.py
  creator/users/schema.py
Labels: refactor

#447 🏷 Release 1.14.0
  CHANGELOG.md
Labels: release

#450 🔥 Remove vault
  Dockerfile
  bin/entrypoint.sh
Labels: feature

#449 ✨ File analyses
  creator/analyses/__init__.py
  creator/analyses/analyzer.py
  creator/analyses/apps.py
  creator/analyses/factories.py
  creator/analyses/migrations/0001_initial.py
  creator/analyses/migrations/0002_analysis_error_message.py
  creator/analyses/migrations/0003_fix_permission_name.py
  creator/analyses/migrations/__init__.py
  creator/analyses/models.py
  creator/analyses/mutations.py
  creator/analyses/schema.py
  creator/files/mutations/file.py
  creator/files/mutations/version.py
  creator/groups.py
  creator/management/commands/schedule_jobs.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/tasks.py
  requirements.txt
  tests/analyses/__init__.py
  tests/analyses/test_create_analysis.py
  tests/analyses/test_file_formats.py
  tests/analyses/test_query.py
  tests/conftest.py
  tests/data/SD_ME0WME0W/FV_4DP2P2Y2_clinical.csv
  tests/data/SD_ME0WME0W/FV_4DP2P2Y2_clinical.tsv
  tests/data/SD_ME0WME0W/FV_4DP2P2Y2_clinical.txt
  tests/data/SD_ME0WME0W/FV_4DP2P2Y2_clinical.xlsx
  tests/files/test_upload.py
  tests/tasks/test_analyze_task.py
Labels: feature

#452 🔧 Add SSL setting to RQ config
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
Labels: devops

#456 ✨ Accept .xls file type for file analysis
  creator/analyses/analyzer.py
  tests/analyses/test_file_formats.py
  tests/data/SD_ME0WME0W/FV_4DP2P2Y2_clinical.xls
Labels: feature

#455 ♻️ Refactor document upload flow
  creator/events/signals.py
  creator/files/migrations/0017_make_fields_optional.py
  creator/files/migrations/0018_add_study_to_version.py
  creator/files/models.py
  creator/files/mutations/file.py
  creator/files/mutations/version.py
  creator/files/schema/version.py
  creator/studies/migrations/0021_add_study_to_version.py
  tests/analyses/test_create_analysis.py
  tests/analyses/test_file_formats.py
  tests/conftest.py
  tests/events/test_files.py
  tests/events/test_versions.py
  tests/files/test_create_file.py
  tests/files/test_delete.py
  tests/files/test_update_files.py
  tests/files/test_update_versions.py
  tests/files/test_upload.py
Labels: refactor

#457 🐛 Determine study from version or file
  creator/analyses/analyzer.py
  creator/analyses/mutations.py
  tests/analyses/test_create_analysis.py
  tests/conftest.py
Labels: bug

#458 🏷 Release 1.14.1
  CHANGELOG.md
Labels: release

#459 🐛 Check view_my_version permissions for downloads
  creator/files/views.py
Labels: bug

#460 🏷 Release 1.14.2
  CHANGELOG.md
Labels: release
