Repository kids-first/kf-api-study-creator, pull requests merged in 2020-04, with the labels that each got.

#365 ✨ Add DBG file type for dbGaP Submission File
  creator/files/migrations/0014_add_dbGaP_type.py
  creator/files/models.py
Labels: feature

#364 🐳 Build and push images to Dockerhub registry
  .github/workflows/dockerimage.yml
  creator/settings/development.py
Labels: devops

#359 🔒 Authorization model
  bin/dev_entrypoint.sh
  bin/entrypoint.sh
  creator/buckets/migrations/0002_add_custom_permissions.py
  creator/buckets/models.py
  creator/buckets/schema.py
  creator/events/migrations/0007_add_custom_permissions.py
  creator/events/models.py
  creator/events/schema.py
  creator/files/migrations/0015_add_custom_permissions.py
  creator/files/models.py
  creator/files/schema/__init__.py
  creator/files/schema/file.py
  creator/files/schema/version.py
  creator/files/views.py
  creator/groups.py
  creator/management/commands/setup_permissions.py
  creator/middleware.py
  creator/migrations/0010_list_all_users_permission.py
  creator/migrations/0011_add_custom_permissions.py
  creator/models.py
  creator/schema.py
  creator/settings/production.py
  creator/studies/migrations/0013_add_custom_permissions.py
  creator/studies/models.py
  creator/studies/schema.py
  creator/users/schema.py
  tests/authentication/test_middleware.py
  tests/buckets/test_bucket_authorization.py
  tests/buckets/test_link_bucket.py
  tests/conftest.py
  tests/events/test_event_auth.py
  tests/events/test_files.py
  tests/events/test_versions.py
  tests/files/test_delete.py
  tests/files/test_dev_tokens.py
  tests/files/test_downloads.py
  tests/files/test_signed_urls.py
  tests/files/test_update_files.py
  tests/files/test_update_versions.py
  tests/files/test_upload.py
  tests/studies/test_collaborators.py
  tests/test_authorized.py
  tests/test_ego_signing.py
  tests/test_query.py
  tests/users/test_groups.py
  tests/users/test_list.py
  tests/users/test_permissions.py
  tests/users/test_profile.py
  tests/users/test_subscriptions.py
  tests/users/test_update.py
Labels: feature, refactor

#370 🔒 Cavatica permissions
  creator/groups.py
  creator/projects/migrations/0006_add_cavatica_permissions.py
  creator/projects/models.py
  creator/projects/schema.py
  tests/projects/test_cavatica_sync.py
  tests/projects/test_import_volume_files.py
  tests/projects/test_link_project.py
  tests/projects/test_new_project.py
  tests/projects/test_query.py
  tests/projects/test_update_project.py
Labels: feature

#371 📝 Update permission docs
  docs/authorization.rst
Labels: documentation

#372 🔒 Add create study permission
  creator/groups.py
Labels: feature

#374 🔒 Add change study permission to Admin group
  creator/groups.py
  docs/authorization.rst
Labels: feature

#375 🔒 Add permissions to study mutations
  creator/studies/schema.py
  tests/studies/test_create_study.py
  tests/studies/test_update_study.py
Labels: feature

#373 ✨ Add development endpoints
  bin/dev_entrypoint.sh
  creator/dev/__init__.py
  creator/dev/urls.py
  creator/dev/views.py
  creator/management/commands/permission_tables.py
  creator/management/commands/setup_test_user.py
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/urls.py
  dev-requirements.txt
  docker-compose.yml
  docs/conf.py
  docs/development/dev_api.rst
  docs/index.rst
  tests/authentication/test_middleware.py
  tests/dev/__init__.py
  tests/dev/conftest.py
  tests/dev/test_change_groups.py
  tests/dev/test_reset_db.py
  tests/files/test_downloads.py
Labels: feature

#376 ✨ Add development endpoint to settings schema
  creator/schema.py
Labels: feature

#377 ✨ Idempotent factories
  creator/buckets/factories.py
  creator/files/factories.py
  creator/studies/factories.py
  creator/studies/management/commands/fakestudies.py
  creator/users/factories.py
  tests/dev/test_reset_db.py
Labels: bug, feature

#378 🐛 Create test user before fake data
  bin/dev_entrypoint.sh
Labels: bug

#379 🐋 Add coordinator service
  docker-compose.coordinator.yml
  docker-compose.yml
  docs/development/quickstart.rst
Labels: devops, documentation

#381 ♻️ Refactor the permission checking for uploading version
  creator/files/schema/version.py
Labels: refactor

#382 ✨ Idempotent test files
  creator/buckets/factories.py
  creator/files/factories.py
  creator/files/management/commands/fakefiles.py
  creator/projects/factories.py
  creator/studies/factories.py
  docker-compose.coordinator.yml
Labels: feature, refactor

#389 🐛 Make fake data reproducible
  creator/files/factories.py
  creator/files/management/commands/fakefiles.py
Labels: bug
