Repository kids-first/kf-api-study-creator, pull requests merged in 2020-09, with the labels that each got.

#467 ✨ Document file_type validation
  creator/analyses/file_types.py
  creator/files/migrations/0019_add_file_type.py
  creator/files/models.py
  creator/files/mutations/file.py
  creator/urls.py
  tests/data/SD_ME0WME0W/s3_scrape.csv
  tests/data/SD_ME0WME0W/s3_scrape_extra.csv
  tests/data/SD_ME0WME0W/s3_scrape_partial.csv
  tests/files/test_file_type_validation.py
Labels: feature

#468 ✨ Valid types field
  creator/files/models.py
  creator/files/mutations/file.py
  creator/files/nodes/file.py
  creator/files/nodes/version.py
  tests/conftest.py
  tests/data/SD_ME0WME0W/s3_scrape.csv
  tests/events/test_files.py
  tests/files/test_create_file.py
  tests/files/test_file_type_validation.py
  tests/files/test_update_files.py
  tests/files/test_valid_types.py
Labels: feature

#470 🐛 Fix referral token exceptions
  creator/referral_tokens/mutations.py
  creator/urls.py
Labels: bug

#471 🔧 Migrated to standard deployment
  Jenkinsfile
  JenkinsfileWorker
  bin/entrypoint.sh
Labels: devops

#474 🏷 Release 1.14.3
  CHANGELOG.md
Labels: release

#472 ✨ Add download extract config endpoint
  creator/analyses/file_types.py
  creator/extract_configs/templates/s3_scrape_config.py
  creator/extract_configs/views.py
  creator/files/migrations/0020_version_extract_config_permission.py
  creator/files/models.py
  creator/groups.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/urls.py
  tests/data/s3_scrape_config_file.py
  tests/files/test_extract_config.py
Labels: feature

#475 ✨ New expedited types
  creator/analyses/file_types.py
  creator/extract_configs/templates/family_trio_config.py
  creator/extract_configs/templates/participant_config.py
  creator/files/migrations/0021_add_file_types.py
  creator/files/models.py
Labels: feature

#480 🔧 Get stage from environment
  creator/settings/production.py
Labels: devops

#481 🏷 Release 1.14.4
  CHANGELOG.md
Labels: release

#483 🐛 Stringify before checking for printable chars
  creator/files/models.py
Labels: bug

#484 🏷 Release 1.14.5
  CHANGELOG.md
Labels: release
