Repository kids-first/kf-api-study-creator, pull requests merged in 2020-06, with the labels that each got.

#404 🔧 Add slack job
  creator/management/commands/schedule_jobs.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/slack.py
  creator/tasks.py
Labels: feature

#406 🐛 Fix email settings
  bin/entrypoint.sh
Labels: bug

#407 🐛 Use proper email settings
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
Labels: bug

#408 🖼 Update email picture
  creator/email/templates/base.html
Labels: feature

#409 📦 Use SES email backend
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  requirements.txt
Labels: bug

#411 ✏️ Correct typo in email
  creator/email/templates/invite.html
Labels: bug

#412 🖼 Shrink email header image
  creator/email/templates/base.html
Labels: devops, refactor

#413 🏷 Release 1.11.0
  CHANGELOG.md
Labels: release

#410 ✨ Create daily Slack postings for study updates
  bin/dev_worker.sh
  bin/worker.conf
  creator/management/commands/schedule_jobs.py
  creator/slack.py
  creator/tasks.py
  tests/tasks/test_slack_notify_task.py
Labels: feature

#415 🔊Task logging
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/slack.py
  creator/studies/dataservice.py
Labels: refactor

#419 ♻️ Auto join Slack channels
  creator/management/commands/schedule_jobs.py
  creator/slack.py
  creator/tasks.py
Labels: bug, refactor

#420 📈 Add utm tracking to slack pins
  creator/slack.py
Labels: feature

#421 🏷 Release 1.11.1
  .github/workflows/gh_release.yml
  CHANGELOG.md
Labels: release

#422 ♻️ Improve verbosity of collaborator events
  creator/studies/mutations.py
Labels: refactor

#424 🔥 Remove default Cavatica projects for new studies
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  docs/cavatica.rst
  tests/events/test_studies.py
  tests/projects/test_cavatica.py
Labels: refactor
