Repository kids-first/kf-api-study-creator, pull requests merged in 2020-11, with the labels that each got.

#505 🏷 Release 1.14.6
  CHANGELOG.md
Labels: release

#509 ✨ Kill rq jobs by id
  creator/utils.py
  requirements.txt
  tests/test_utils.py
Labels: feature

#512 🔥 Remove hypothesis testing
  dev-requirements.txt
  tests/studies/test_create_study.py
  tests/studies/test_update_study.py
Labels: refactor

#511 🔥 Remove ego authentication
  creator/middleware.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/authentication/test_middleware.py
  tests/conftest.py
  tests/users/test_create.py
  tests/users/test_profile.py
Labels: refactor

#514 🐛 Fix events query for non-admins
  creator/events/schema.py
Labels: bug

#516 🏷 Release 1.14.7
  CHANGELOG.md
Labels: release

#486 ✨ Releases application
  bin/dev_entrypoint.sh
  bin/dev_worker.sh
  bin/entrypoint.sh
  bin/worker.conf
  creator/authentication.py
  creator/decorators.py
  creator/dev/views.py
  creator/groups.py
  creator/jobs/models.py
  creator/management/commands/schedule_jobs.py
  creator/releases/__init__.py
  creator/releases/apps.py
  creator/releases/factories.py
  creator/releases/management/commands/fakereleases.py
  creator/releases/migrations/0001_initial.py
  creator/releases/migrations/0002_add_release_events.py
  creator/releases/migrations/0003_add_release_log.py
  creator/releases/migrations/__init__.py
  creator/releases/models.py
  creator/releases/mutations.py
  creator/releases/nodes.py
  creator/releases/queries.py
  creator/releases/schema.py
  creator/releases/signals.py
  creator/releases/slack.py
  creator/releases/tasks.py
  creator/releases/validators.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/status/schema.py
  creator/studies/nodes.py
  docs/index.rst
  docs/releases/introduction.rst
  docs/releases/process.rst
  requirements.txt
  tests/authentication/test_service_auth.py
  tests/decorators.py
  tests/releases/test_cancel_release.py
  tests/releases/test_check_release.py
  tests/releases/test_check_task.py
  tests/releases/test_publish_release.py
  tests/releases/test_release_cancel_tasks.py
  tests/releases/test_release_event_queries.py
  tests/releases/test_release_event_signals.py
  tests/releases/test_release_initialize_tasks.py
  tests/releases/test_release_service_mutations.py
  tests/releases/test_release_service_queries.py
  tests/releases/test_release_start_tasks.py
  tests/releases/test_release_task.py
  tests/releases/test_release_task_queries.py
  tests/releases/test_releases_queries.py
  tests/releases/test_scan_releases.py
  tests/releases/test_slack.py
  tests/releases/test_start_release.py
  tests/releases/test_update_release.py
  tests/releases/test_validators.py
  tests/test_not_found.py
  tests/users/test_permissions.py
Labels: feature
