Repository kids-first/kf-api-study-creator, pull requests merged in 2020-07, with the labels that each got.

#425 🏷 Release 1.12.0
  CHANGELOG.md
  release_maker_cfg.json
Labels: release

#423 ✨ Collaborator roles
  creator/events/migrations/0013_updated_event_types.py
  creator/events/models.py
  creator/projects/cavatica.py
  creator/projects/schema.py
  creator/referral_tokens/schema.py
  creator/studies/management/commands/fakestudies.py
  creator/studies/migrations/0019_add_through_relationship.py
  creator/studies/migrations/0020_add_collaborator_role.py
  creator/studies/models.py
  creator/studies/mutations.py
  creator/studies/nodes.py
  creator/tasks.py
  creator/users/schema.py
  docs/authorization.rst
  requirements.txt
  tests/files/test_update_files.py
  tests/files/test_upload.py
  tests/projects/test_query.py
  tests/referral_tokens/test_exchange_referral_token.py
  tests/studies/test_collaborators.py
  tests/test_authorized.py
  tests/test_query.py
  tests/users/test_membership.py
Labels: feature

#426 🗃️ Patch collaborator mutation
  creator/studies/migrations/0019_add_through_relationship.py
Labels: bug

#428 ✨ Add file and collaborator details to slack notification
  creator/slack.py
Labels: feature

#429 ♻️ Separate update version permission to change meta and change status
  creator/files/migrations/0016_version_mutation_permission.py
  creator/files/models.py
  creator/files/schema/version.py
  creator/groups.py
  tests/files/test_update_versions.py
Labels: refactor

#430 🏷 Release 1.13.0
  CHANGELOG.md
Labels: release

#433 🐛 Fix file link in slack updates
  creator/slack.py
Labels: bug

#439 🐛 Fix referral token event message with f-string
  creator/referral_tokens/schema.py
Labels: bug

#438 ✨ Specify what change was made to a document in event message
  creator/files/schema/file.py
Labels: refactor

#437 ♻️ Shift slack messages timestamp to be US/Eastern timezone
  creator/slack.py
Labels: refactor
