Repository kids-first/kf-api-study-creator, pull requests merged in 2021-04, with the labels that each got.

#610 🔥 Remove lingering ego auth fields
  creator/groups.py
  creator/middleware.py
  creator/migrations/0013_drop_ego_fields.py
  creator/models.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/studies/migrations/0023_add_subscription_permissions.py
  creator/studies/models.py
  creator/users/factories.py
  creator/users/mutations.py
  creator/users/schema.py
  tests/authentication/test_middleware.py
  tests/tasks/test_import_delivery_files_task.py
  tests/test_fields.py
  tests/users/test_create.py
  tests/users/test_fields.py
  tests/users/test_list.py
  tests/users/test_profile.py
  tests/users/test_subscriptions.py
Labels: refactor

#614 🏷 Release 1.16.0
  CHANGELOG.md
Labels: release

#612 ✨ Save services as users
  creator/authentication.py
  creator/middleware.py
  creator/releases/models.py
  creator/releases/tasks.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/authentication/test_client_credentials_auth.py
  tests/releases/test_release_task.py
  tests/users/test_create.py
Labels: feature

#615 🏷 Release 1.17.0
  CHANGELOG.md
Labels: release

#498 ✨ New ingest runs app
  .coveragerc
  bin/dev_worker.sh
  bin/worker.conf
  creator/data_reviews/factories.py
  creator/events/migrations/0015_add_ingest_run_events.py
  creator/events/migrations/0016_add_ingest_run_fk.py
  creator/events/migrations/0017_add_validation_run_events.py
  creator/events/models.py
  creator/groups.py
  creator/ingest_runs/__init__.py
  creator/ingest_runs/apps.py
  creator/ingest_runs/common/__init__.py
  creator/ingest_runs/common/model.py
  creator/ingest_runs/factories.py
  creator/ingest_runs/migrations/0001_initial.py
  creator/ingest_runs/migrations/0002_refactor_to_ingest_process.py
  creator/ingest_runs/migrations/0003_add_validation_models.py
  creator/ingest_runs/migrations/__init__.py
  creator/ingest_runs/models/__init__.py
  creator/ingest_runs/models/ingest_run.py
  creator/ingest_runs/models/validation_run.py
  creator/ingest_runs/mutations.py
  creator/ingest_runs/nodes.py
  creator/ingest_runs/queries.py
  creator/ingest_runs/schema.py
  creator/ingest_runs/signals.py
  creator/ingest_runs/tasks.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/features.py
  creator/settings/production.py
  creator/settings/testing.py
  creator/studies/data_generator/__init__.py
  creator/studies/data_generator/ingest_package/__init__.py
  creator/studies/data_generator/ingest_package/extract_configs/__init__.py
  creator/studies/data_generator/ingest_package/extract_configs/biospec.py
  creator/studies/data_generator/ingest_package/extract_configs/genomic.py
  creator/studies/data_generator/ingest_package/extract_configs/s3_scrape_config.py
  creator/studies/data_generator/ingest_package/ingest_package_config.py
  creator/studies/data_generator/ingest_package/transform_module.py
  creator/studies/data_generator/study_generator.py
  requirements.txt
  tests/conftest.py
  tests/ingest_runs/test_common.py
  tests/ingest_runs/test_ingest_runs_mutations.py
  tests/ingest_runs/test_ingest_runs_queries.py
  tests/ingest_runs/test_model.py
  tests/ingest_runs/test_signals.py
  tests/ingest_runs/test_tasks.py
  tests/ingest_runs/test_validation_run_model.py
  tests/studies/test_study_generator.py
  tests/test_not_found.py
Labels: feature

#613 ✨ Validation GraphQL API
  creator/data_reviews/migrations/0002_add_study_permissions.py
  creator/data_reviews/models.py
  creator/data_reviews/nodes.py
  creator/groups.py
  creator/ingest_runs/common/mutations.py
  creator/ingest_runs/factories.py
  creator/ingest_runs/mutations/__init__.py
  creator/ingest_runs/mutations/ingest_run.py
  creator/ingest_runs/mutations/validation_run.py
  creator/ingest_runs/nodes/__init__.py
  creator/ingest_runs/nodes/ingest_run.py
  creator/ingest_runs/nodes/validation_resultset.py
  creator/ingest_runs/nodes/validation_run.py
  creator/ingest_runs/queries/__init__.py
  creator/ingest_runs/queries/ingest_run.py
  creator/ingest_runs/queries/validation_run.py
  creator/ingest_runs/schema.py
  creator/ingest_runs/tasks/__init__.py
  creator/ingest_runs/tasks/ingest_run.py
  creator/ingest_runs/tasks/validation_run.py
  creator/ingest_runs/views.py
  creator/urls.py
  tests/conftest.py
  tests/data/sample_validation_report.md
  tests/data_reviews/test_data_reviews_mutations.py
  tests/data_reviews/test_data_reviews_queries.py
  tests/ingest_runs/test_common.py
  tests/ingest_runs/test_ingest_runs_mutations.py
  tests/ingest_runs/test_tasks.py
  tests/ingest_runs/test_validation_result_downloads.py
  tests/ingest_runs/test_validation_run_model.py
  tests/ingest_runs/test_validation_runs_mutations.py
  tests/ingest_runs/test_validation_runs_queries.py
  tests/test_not_found.py
Labels: feature

#621 🐛 Don't refetch tokens every request
  creator/authentication.py
  tests/authentication/test_client_credentials_auth.py
Labels: bug

#622 🏷 Release 1.17.1
  CHANGELOG.md
Labels: release

#625 ⬆️ Upgrade Sentry sdk
  requirements.txt
Labels: refactor

#628 ✨ Add debug middleware
  creator/schema.py
  creator/settings/development.py
  tests/test_debug_middleware.py
Labels: feature

#620 🔊 Warn instead of raising exception
  creator/tasks.py
  tests/tasks/test_analyze_task.py
Labels: refactor

#630 ♻️ Condense status check logs
  creator/decorators.py
Labels: refactor

#618 📝 Add RFC for Organization
  docs/_static/images/OrganizationModel.png
  docs/rfcs/0001_organizations.md
Labels: documentation
