Repository kids-first/kf-api-study-creator, pull requests merged in 2021-09, with the labels that each got.

#738 💬 Add user to template event description
  creator/data_templates/signals.py
Labels: refactor

#730 ✨ Add endpoint to download template versions
  creator/data_templates/packaging.py
  creator/data_templates/views.py
  creator/urls.py
  tests/data_templates/test_download_templates.py
  tests/data_templates/test_package_templates.py
Labels: feature

#739 🐛 Delete templates in faketemplates cmd if flag is given
  creator/data_templates/management/commands/faketemplates.py
  tests/data_templates/test_commands.py
Labels: bug

#740 🏷 Release 1.19.4
  CHANGELOG.md
Labels: release

#742 ♻️ Refactor validation to use templates
  creator/ingest_runs/tasks/validation_run.py
  tests/ingest_runs/test_validation.py
Labels: refactor

#746 🐛 Fix processing of missing value list
  creator/data_templates/factories.py
  creator/data_templates/models.py
  tests/data_templates/test_template_models.py
Labels: bug

#748 🏷 Release 1.19.5
  CHANGELOG.md
Labels: release

#753 ♻️ Adjust validation rules and report
  creator/ingest_runs/tasks/validation_run.py
  creator/ingest_runs/validation_rules.py
  requirements.txt
Labels: refactor

#761 🔊 Configure release task logging directly
  creator/settings/production.py
Labels: refactor

#757 🏷 Release 1.19.6
  CHANGELOG.md
Labels: release

#763 ♻️ Omit Content-Length header in download validation report
  creator/ingest_runs/tasks/validation_run.py
  creator/ingest_runs/views.py
  tests/ingest_runs/test_validation_result_downloads.py
Labels: refactor

#767 🐛 Fix writing of job logs in local development
  creator/jobs/models.py
  tests/decorators.py
Labels: bug

#769 🏷 Release 1.19.7
  CHANGELOG.md
Labels: release

#774 🔥 Remove sync job with old release coordinator
  creator/management/commands/schedule_jobs.py
  creator/releases/tasks.py
Labels: refactor
