Repository kids-first/kf-api-study-creator, pull requests merged in 2021-08, with the labels that each got.

#699 ✨ Template Field Definition Validation
  creator/data_templates/factories.py
  creator/data_templates/field_definitions_schema.py
  creator/data_templates/models.py
  requirements.txt
  tests/data_templates/test_field_definitions.py
  tests/data_templates/test_template_version_mutations.py
Labels: feature

#710 ✨ Download study templates
  creator/data_templates/field_definitions_schema.py
  creator/data_templates/models.py
  creator/data_templates/packaging.py
  creator/data_templates/views.py
  creator/urls.py
  requirements.txt
  tests/data_templates/test_download_templates.py
  tests/data_templates/test_field_definitions.py
  tests/data_templates/test_package_templates.py
  tests/data_templates/test_template_models.py
Labels: feature

#703 ✨ Add User organization filter
  creator/organizations/mutations.py
  creator/organizations/queries.py
  creator/users/queries.py
  creator/users/schema.py
  tests/users/test_queries.py
Labels: feature

#711 ✨ Upload field definitions
  creator/data_templates/management/commands/__init__.py
  creator/data_templates/management/commands/faketemplates.py
  creator/data_templates/management/template_package.xlsx
  creator/data_templates/migrations/0002_template_version_desc_nullable.py
  creator/data_templates/models.py
  creator/data_templates/mutations/template_version.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/data_templates/test_commands.py
  tests/data_templates/test_template_models.py
  tests/data_templates/test_template_version_mutations.py
  tests/data_templates/test_upload_fields.py
  tests/events/test_versions.py
Labels: feature

#718 🏷 Release 1.19.0
  CHANGELOG.md
Labels: release

#721 ⬆️ Upgrade sentry
  requirements.txt
Labels: refactor

#726 🔊 Configure TaskLogger directly
  creator/settings/production.py
Labels: devops

#729 🏷 Release 1.19.1
  CHANGELOG.md
Labels: release

#731 🐛 Permit all non-machine roles to view and list templates
  creator/groups.py
  tests/data_templates/test_data_templates_queries.py
Labels: bug

#732 🏷 Release 1.19.2
  CHANGELOG.md
Labels: release
