Repository kids-first/kf-api-study-creator, pull requests merged in 2021-07, with the labels that each got.

#684 ✨ Add mutation to transfer study to another organization
  creator/events/models.py
  creator/organizations/mutations.py
  creator/studies/mutations.py
  tests/organizations/test_add_remove_member.py
  tests/studies/test_transfer_study.py
Labels: feature

#690 🐛 Fix order of organization migrations
  creator/buckets/migrations/0003_add_organizations.py
  creator/events/migrations/0019_add_organizations.py
  creator/referral_tokens/migrations/0002_add_organizations.py
Labels: bug

#687 ♻️ Remove obsolete file types
  creator/analyses/file_types.py
  creator/files/factories.py
  creator/files/migrations/0024_set_old_types_to_oth.py
  creator/files/migrations/0025_remove_old_file_type_choices.py
  creator/files/models.py
  tests/files/test_valid_types.py
Labels: refactor

#692 🔧 Increase max number of relay connections
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
Labels: bug

#695 🏷 Release 1.18.0
  CHANGELOG.md
Labels: release

#696 🔧 Run scheduler without supervisor
  bin/entrypoint.sh
Labels: bug, devops

#697 🏷 Release 1.18.1
  CHANGELOG.md
Labels: release

#682 ✨ Initial template management API
  creator/data_templates/__init__.py
  creator/data_templates/apps.py
  creator/data_templates/factories.py
  creator/data_templates/migrations/0001_initial.py
  creator/data_templates/migrations/__init__.py
  creator/data_templates/models.py
  creator/data_templates/mutations/__init__.py
  creator/data_templates/mutations/data_template.py
  creator/data_templates/mutations/template_version.py
  creator/data_templates/nodes/__init__.py
  creator/data_templates/nodes/data_template.py
  creator/data_templates/nodes/template_version.py
  creator/data_templates/queries/__init__.py
  creator/data_templates/queries/data_template.py
  creator/data_templates/queries/template_version.py
  creator/data_templates/schema.py
  creator/data_templates/signals.py
  creator/events/migrations/0020_add_template_events.py
  creator/events/models.py
  creator/groups.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/data_templates/test_data_templates_mutations.py
  tests/data_templates/test_data_templates_queries.py
  tests/data_templates/test_template_signals.py
  tests/data_templates/test_template_version_mutations.py
  tests/data_templates/test_template_version_queries.py
Labels: feature

#698 ♻️ Limit length of Slack notifications
  creator/slack.py
Labels: refactor

#693 ✨Add mutations to link/unlink templates to/from studies
  creator/data_templates/mutations/study_templates.py
  creator/data_templates/mutations/template_version.py
  creator/data_templates/schema.py
  tests/data_templates/test_study_template_mutations.py
  tests/data_templates/test_template_version_mutations.py
Labels: feature

#705 ♻️ Relax required columns in file types
  creator/analyses/file_types.py
  creator/extract_configs/templates/aliquot_manifest_config.py
  creator/extract_configs/templates/biobank_manifest_config.py
  creator/extract_configs/templates/biospecimen_collection_manifest_config.py
  creator/extract_configs/templates/general_observations_config.py
  creator/extract_configs/templates/participant_config.py
  creator/extract_configs/templates/participant_diseases_config.py
  creator/extract_configs/templates/participant_phenotypes_config.py
  creator/extract_configs/templates/sequencing_manifest_config.py
  tests/extract_configs/test_extract_configs.py
Labels: refactor

#706 🏷 Release 1.18.2
  CHANGELOG.md
Labels: release

#708 ✨ Create users subquery for Organization queries
  creator/organizations/nodes.py
  tests/organizations/test_organizations_queries.py
Labels: feature
