Repository kids-first/kf-api-study-creator, pull requests merged in 2021-12, with the labels that each got.

#789 ✨ Add short_code, domain, and program to Study
  creator/studies/factories.py
  creator/studies/migrations/0027_add_short_code.py
  creator/studies/migrations/0028_populate_short_code.py
  creator/studies/migrations/0029_add_populate_domain.py
  creator/studies/migrations/0030_add_and_populate_program.py
  creator/studies/migrations/0031_patch_dataservice.py
  creator/studies/migrations/study_metadata.csv
  creator/studies/models.py
  creator/studies/mutations.py
  tests/events/test_studies.py
  tests/studies/test_create_study.py
  tests/studies/test_update_study.py
Labels: feature

#804 🛠 Expose content-disposition header in download template reqs
  creator/data_templates/views.py
Labels: refactor

#802 🏷 Release 1.21.0
  CHANGELOG.md
Labels: release

#805 🗃 Fix study domains from prev domain migration
  creator/studies/migrations/0032_fix_populate_domain.py
Labels: refactor

#806 🏷 Release 1.21.1
  CHANGELOG.md
Labels: release
