Repository kids-first/kf-api-study-creator, pull requests merged in 2021-06, with the labels that each got.

#655 ♻️ Add study attribute to IngestProcess
  creator/ingest_runs/common/model.py
  tests/ingest_runs/test_common.py
Labels: refactor

#571 ✨ Add new doc types and extract configs
  creator/analyses/file_types.py
  creator/extract_configs/__init__.py
  creator/extract_configs/templates/aliquot_manifest_config.py
  creator/extract_configs/templates/biobank_manifest_config.py
  creator/extract_configs/templates/biospecimen_collection_manifest_config.py
  creator/extract_configs/templates/complex_family_config.py
  creator/extract_configs/templates/family_trio_config.py
  creator/extract_configs/templates/general_observations_config.py
  creator/extract_configs/templates/genomic_workflow_output_manifest_config.py
  creator/extract_configs/templates/participant_config.py
  creator/extract_configs/templates/participant_diseases_config.py
  creator/extract_configs/templates/participant_phenotypes_config.py
  creator/extract_configs/templates/s3_scrape_config.py
  creator/extract_configs/templates/sequencing_manifest_config.py
  creator/files/migrations/0023_add_document_types.py
  creator/files/models.py
  creator/studies/data_generator/ingest_package/extract_configs/aliquot_manifest_config.py
  creator/studies/data_generator/ingest_package/extract_configs/biobank_manifest_config.py
  creator/studies/data_generator/ingest_package/extract_configs/biospec.py
  creator/studies/data_generator/ingest_package/extract_configs/biospecimen_collection_manifest_config.py
  creator/studies/data_generator/ingest_package/extract_configs/complex_family_config.py
  creator/studies/data_generator/ingest_package/extract_configs/family_trio_config.py
  creator/studies/data_generator/ingest_package/extract_configs/genomic.py
  creator/studies/data_generator/ingest_package/extract_configs/participant_config.py
  creator/studies/data_generator/ingest_package/extract_configs/participant_diseases_config.py
  creator/studies/data_generator/ingest_package/extract_configs/participant_phenotypes_config.py
  creator/studies/data_generator/ingest_package/extract_configs/s3_scrape_config.py
  creator/studies/data_generator/ingest_package/extract_configs/sequencing_manifest_config.py
  creator/studies/data_generator/ingest_package/transform_module.py
  creator/studies/data_generator/study_generator.py
  pytest.ini
  requirements.txt
  tests/extract_configs/__init__.py
  tests/extract_configs/fixtures.py
  tests/extract_configs/test_downloads.py
  tests/extract_configs/test_extract_configs.py
  tests/files/test_valid_types.py
Labels: feature

#665 ⬆️ Bump Django version to fix regression
  creator/files/models.py
  creator/ingest_runs/models/validation_run.py
  requirements.txt
  tests/conftest.py
  tests/files/test_upload.py
Labels: bug

#664 ♻️ Fix pandas indexing warnings
  creator/ingest_runs/genomic_data_loader.py
Labels: refactor

#662 ♻️ Add timezone to Banner mutation datetimes
  creator/status/banners/mutations.py
  tests/status/test_banner_mutations.py
Labels: refactor

#660 ♻️ Overwrite S3 files when appending
  creator/files/mutations/version.py
  creator/settings/production.py
  tests/files/test_upload.py
Labels: refactor

#670 ⬆️ Bump pytest and ingest library versions
  creator/ingest_runs/genomic_data_loader.py
  dev-requirements.txt
  pytest.ini
  requirements.txt
  setup.cfg
  tests/authentication/test_middleware.py
  tests/buckets/test_buckets.py
  tests/conftest.py
  tests/ingest_runs/test_genomic_data_loader.py
Labels: devops

#671 👷 Cache dependencies in CircleCI
  .circleci/config.yml
Labels: devops

#672 ✨ Add node query for querying nodes
  creator/schema.py
Labels: feature

#667 ♻️ Address graphene and markdown warnings
  .circleci/config.yml
  creator/files/nodes/file.py
Labels: refactor

#617 ✨ Data review file validation task
  creator/data_reviews/mutations.py
  creator/events/migrations/0018_add_intermed_ingest_process_states.py
  creator/events/models.py
  creator/files/models.py
  creator/ingest_runs/common/model.py
  creator/ingest_runs/common/mutations.py
  creator/ingest_runs/factories.py
  creator/ingest_runs/migrations/0004_add_ingest_error_msg.py
  creator/ingest_runs/migrations/0005_add_modified_at.py
  creator/ingest_runs/models/__init__.py
  creator/ingest_runs/models/validation_run.py
  creator/ingest_runs/mutations/ingest_run.py
  creator/ingest_runs/mutations/validation_run.py
  creator/ingest_runs/nodes/__init__.py
  creator/ingest_runs/queries/validation_run.py
  creator/ingest_runs/schema.py
  creator/ingest_runs/signals.py
  creator/ingest_runs/tasks/__init__.py
  creator/ingest_runs/tasks/ingest_run.py
  creator/ingest_runs/tasks/validation_run.py
  creator/ingest_runs/views.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  requirements.txt
  tests/data_reviews/test_data_reviews_mutations.py
  tests/events/test_event_auth.py
  tests/ingest_runs/test_common.py
  tests/ingest_runs/test_ingest_runs_mutations.py
  tests/ingest_runs/test_signals.py
  tests/ingest_runs/test_tasks.py
  tests/ingest_runs/test_validation.py
  tests/ingest_runs/test_validation_result_downloads.py
  tests/ingest_runs/test_validation_run_model.py
  tests/ingest_runs/test_validation_runs_mutations.py
  tests/ingest_runs/test_validation_runs_queries.py
  tests/users/test_permissions.py
Labels: feature

#681 ✨ Sort studies by last active
  creator/studies/nodes.py
  creator/studies/schema.py
  tests/studies/test_study_queries.py
Labels: feature

#680 🐛 Update Study model to auto-populate created_at
  creator/studies/migrations/0026_update_studies_created_at.py
  creator/studies/models.py
Labels: bug
