Repository kids-first/kf-api-study-creator, pull requests merged in 2021-01, with the labels that each got.

#532 🔥 Remove dotenv
  manage.py
  requirements.txt
Labels: refactor

#506 ✨ Add ingest run jobs
  .dockerignore
  bin/dev_worker.sh
  bin/worker.conf
  creator/ingest_runs/factories.py
  creator/ingest_runs/migrations/0001_initial.py
  creator/ingest_runs/models.py
  creator/ingest_runs/mutations.py
  creator/ingest_runs/signals.py
  creator/ingest_runs/tasks.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/ingest_runs/test_ingest_runs_mutations.py
  tests/ingest_runs/test_model.py
  tests/ingest_runs/test_signals.py
  tests/ingest_runs/test_tasks.py
Labels: feature

#533 🔥 Remove dotenv from WSGI
  creator/wsgi.py
Labels: bug

#534 🐛 Initialize action should result in pending state
  creator/releases/models.py
  creator/releases/tasks.py
  tests/releases/test_check_release.py
  tests/releases/test_release_initialize_tasks.py
  tests/releases/test_release_start_tasks.py
Labels: bug

#536 🔈 Warn when log file not found
  creator/decorators.py
Labels: bug

#537 🔈 Make log IO errors less strict
  creator/decorators.py
Labels: bug, refactor

#538 📦 Install sentry
  creator/decorators.py
  creator/settings/production.py
  requirements.txt
  tests/studies/test_create_study.py
Labels: devops

#535 👷‍♂️ Updated module version
  JenkinsfileWorker
Labels: devops

#540 ♻️ Don't delete job logs
  creator/decorators.py
  creator/releases/migrations/0004_remove_delete_cascade.py
  creator/releases/models.py
Labels: refactor

#542 🔇 Lower verbosity of auth errors
  creator/middleware.py
  tests/authentication/test_middleware.py
  tests/conftest.py
Labels: refactor

#544 🐛 Use same user throughout test
  tests/studies/test_create_study.py
Labels: bug

#543 🔧 Try to remove old job on start up
  creator/management/commands/schedule_jobs.py
Labels: devops

#539 🔇 Ignore GraphQLError in sentry
  creator/settings/production.py
Labels: devops

#541 🔧 Notify sentry of releases
  .github/workflows/gh_release.yml
Labels: devops

#547 ✉️ Set default from address for tests
  creator/settings/development.py
  creator/settings/testing.py
Labels: bug

#546 ✨ Delete banners
  creator/status/banners/mutations.py
  tests/status/test_banner_mutations.py
  tests/status/test_banner_queries.py
  tests/test_not_found.py
Labels: feature

#552 ✨ Add more filters for JobLog
  creator/jobs/schema.py
Labels: feature

#545 🐛 Handle cases where redis scheduler returns None
  creator/jobs/models.py
  tests/jobs/test_models.py
Labels: bug
