Repository kids-first/kf-api-study-creator, pull requests merged in 2021-02, with the labels that each got.

#562 🔥 Remove references to the Release Coordinator
  docker-compose.coordinator.yml
  docs/development/quickstart.rst
  docs/index.rst
Labels: refactor

#556 ♻️ Only block new tokens if there is an open invite
  creator/referral_tokens/mutations.py
  tests/referral_tokens/test_new_referral_token.py
Labels: bug, refactor

#558 ✨ Attach users to Sentry
  creator/middleware.py
  creator/settings/production.py
  tests/test_middleware.py
Labels: feature

#560 🔊 Rename Sentry transactions with operation name
  creator/settings/production.py
  creator/urls.py
  creator/views.py
Labels: devops

#564 🐛 Add safeguards for trace sampler
  creator/settings/production.py
Labels: bug

#566 🐛 Only verify release id if its in the response
  creator/releases/models.py
Labels: bug

#567 💄 Clean up release messages
  creator/releases/slack.py
Labels: refactor

#577 🐳 Switch to python:3.8-slim-buster docker img
  Dockerfile
  Jenkinsfile
Labels: devops

#578 ⬆️ Bump boto3 and requests
  requirements.txt
Labels: refactor

#579 🐛 Fix bugs from switching to Debian image
  Dockerfile
  JenkinsfileWorker
  bin/dev_entrypoint.sh
  bin/dev_worker.sh
  bin/entrypoint.sh
  bin/scheduler.conf
Labels: bug

#573 🔧 Add settings to status schema
  creator/status/settings/nodes.py
  creator/status/settings/queries.py
Labels: feature

#580 🔧 Add flag to enabled/disable DR bucket creation
  creator/buckets/buckets.py
  creator/settings/features.py
  creator/status/settings/nodes.py
  creator/status/settings/queries.py
  tests/buckets/test_buckets.py
Labels: devops

#581 ✨ Add investigator name to study
  creator/studies/migrations/0022_add_investigator_name.py
  creator/studies/models.py
  creator/studies/mutations.py
  creator/studies/nodes.py
Labels: feature

#582 🏷 Release 1.15.0
  CHANGELOG.md
Labels: release

#574 ✨ Initial DataReview GraphQL API
  creator/data_reviews/__init__.py
  creator/data_reviews/apps.py
  creator/data_reviews/factories.py
  creator/data_reviews/migrations/0001_initial.py
  creator/data_reviews/migrations/__init__.py
  creator/data_reviews/models.py
  creator/data_reviews/mutations.py
  creator/data_reviews/nodes.py
  creator/data_reviews/queries.py
  creator/data_reviews/schema.py
  creator/data_reviews/signals.py
  creator/events/migrations/0014_add_data_review.py
  creator/events/models.py
  creator/groups.py
  creator/schema.py
  creator/settings/development.py
  creator/settings/production.py
  creator/settings/testing.py
  tests/data_reviews/test_data_reviews_events.py
  tests/data_reviews/test_data_reviews_mutations.py
  tests/data_reviews/test_data_reviews_queries.py
  tests/data_reviews/test_data_reviews_signals.py
Labels: feature

#587 🔥 Remove build_environments for worker
  JenkinsfileWorker
Labels: devops

#586 🐛 Add missing import
  creator/analyses/analyzer.py
  tests/analyses/test_extract_data.py
Labels: bug

#589 🏷 Release 1.15.1
  CHANGELOG.md
Labels: release
