Repository kids-first/kf-api-study-creator, pull requests merged in 2021-03, with the labels that each got.

#594 🔧 Increase timeout for Cavatica tasks
  creator/settings/production.py
Labels: devops

#591 ⬆️ Upgrade slack sdk
  creator/releases/slack.py
  creator/slack.py
  requirements.txt
  tests/tasks/test_slack_notify_task.py
Labels: bug, refactor

#595 👷 Add new workflow for sentry releases
  .github/workflows/gh_release.yml
  .github/workflows/sentry.yml
Labels: devops

#596 🏷 Release 1.15.2
  CHANGELOG.md
Labels: release

#592 ✨ Set download endpoints to use http in dev mode
  creator/files/nodes/file.py
  creator/files/nodes/version.py
  creator/jobs/schema.py
  tests/files/test_downloads.py
  tests/jobs/test_job_downloads.py
Labels: feature

#601 ✨ Make events in data_review node sortable with EventFilter
  creator/data_reviews/nodes.py
Labels: refactor

#608 ✅ Tests for ingest-app branch and ingest GWO feature flag
  creator/ingest_runs/signals.py
  creator/ingest_runs/tasks.py
  creator/settings/features.py
  tests/ingest_runs/test_ingest_runs_mutations.py
  tests/ingest_runs/test_model.py
  tests/ingest_runs/test_signals.py
  tests/ingest_runs/test_tasks.py
Labels: devops

#607 ✨ Study generator for dev and test
  creator/studies/data_generator/__init__.py
  creator/studies/data_generator/ingest_package/__init__.py
  creator/studies/data_generator/ingest_package/extract_configs/__init__.py
  creator/studies/data_generator/ingest_package/extract_configs/biospec.py
  creator/studies/data_generator/ingest_package/extract_configs/genomic.py
  creator/studies/data_generator/ingest_package/extract_configs/s3_scrape_config.py
  creator/studies/data_generator/ingest_package/ingest_package_config.py
  creator/studies/data_generator/ingest_package/transform_module.py
  creator/studies/data_generator/study_generator.py
  requirements.txt
  tests/studies/test_study_generator.py
Labels: feature
